import {QuizOptions} from './utilsTypes';

export const quizOptions: QuizOptions = {
   NumberQuestions: 10,
   SelectCategory: [
      '일반상식',
      '도서',
      '영화',
      '음악',
      '뮤지컬 & 극장',
      'TV',
      '비디오 게임',
      '보드 게임',
      '자연 & 과학',
      '컴퓨터 공학',
      '수학',
      '신화',
      '스포츠',
      '지리',
      '역사',
      '정치',
      '예술',
      '유명인사',
      '동물',
      '자동차',
      '코믹스',
      '가젯',
      '일본만화',
      '카툰',
   ],
   SelectDifficulty: ['쉬움', '보통', '어려움'],
   SelectType: ['객관식', 'O / X'],
};
