import {QuizOptions} from './utilsTypes';

export const quizOptions: QuizOptions = {
  NumberQuestions: 10,
  SelectCategory: [
    'Any Category',
    'General Knowledge',
    'Entertainment: Books',
    'Entertainment: Film',
    'Entertainment: Music',
    'Entertainment: Musicals & Theatres',
    'Entertainment: Television',
    'Entertainment: Video Games',
    'Entertainment: Board Games',
    'Science & Natur',
    'Science: Computers',
    'Science: Mathematics',
    'Mythology',
    'Sports',
    'Geography',
    'History',
    'Politics',
    'Art',
    'Celebrities',
    'Animals',
    'Vehicles',
    'Entertainment: Comics',
    'Science: Gadgets',
    'Entertainment: Japanese Anime & Manga',
    'Entertainment: Cartoon & Animations',
  ],
  SelectDifficulty: ['Any Difficulty', 'Easy', 'Medium', 'Hard'],
  SelectType: ['Any Type', 'Multiple Choice', 'True / False'],
};
